---
title: Matthew Emvin Taylor
timezone: UTC
collections:
  commercial:
    title: Commercial
    output: true
  featured:
    title: Featured
    output: true
  music-videos:
    title: Music Videos
    output: true
  narrative:
    title: Narrative
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: ''
    type: feature
  values:
    image:
    vimeo:
    director:
    production-company:
    equipment:
    layout: project
    is-shown: true
    is-in-cv: false
- scope:
    path: ''
    type: commercial
  values:
    image:
    vimeo:
    director:
    production-company:
    equipment:
    layout: project
    is-shown: true
    is-in-cv: true
- scope:
    path: ''
    type: narrative
  values:
    layout: narrative
    image:
    vimeo:
    director:
    production-company:
    equipment:
    layout: project
    is-shown: true
    is-in-cv: true
- scope:
    path: ''
    type: music-videos
  values:
    layout: music-videos
    image:
    vimeo:
    director:
    production-company:
    equipment:
    layout: project
    is-shown: true
    is-in-cv: true
url: https://www.matthewemvintaylor.com
baseurl: 
description: "Award-winning London based cinematographer. Represented worldwide by Wizzo & Co"
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Matthew Emvin Taylor
job-title: Cinematographer
email: info@matthewemvintaylor.com
google_site_verification: FXdg3jdY5dYavx-FqZMeT9_TGb2Brq6rmyqQEbBlO7M
analytics: UA-113164652-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%Y"
future: true
social:
  instagram: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false