---
title: Matthew Emvin Taylor
timezone: UTC
collections:
  commercial:
    title: Commercial
    output: true
  music-videos:
    title: Music Videos
    output: true
  narrative:
    title: Narrative
    output: true
  featured:
    title: Featured
    output: true
  posts:
    title: Posts
    output: flase
  uploads:
    title: Uploads
    output: false
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "commercial"
    values:
      layout: "commercial"
      master: true
  - scope:
      path: ""
      type: "narrative"
    values:
      layout: "narrative"
      master: true
  - scope:
      path: ""
      type: "music-videos"
    values:
      layout: "music-videos"
      master: true
url: https://www.matthewemvintaylor.com
baseurl: 
description: London-based cinematographer with worldwide experience.
permalink: pretty
exclude:
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
- assets/scss
plugins:
- jekyll-paginate-v2
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  auto_ids: false
  input: GFM
  hard_wrap: false
highlighter: rouge
colophon: http://garethjohnsdesign.com
company: Matthew Emvin Taylor
job-title: Cinematographer
email: info@matthewemvintaylor.com
google_site_verification: 
analytics: 
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%Y"
future: true
social:
  instagram: 
compress_html:
  comments:
  - "<!-- "
  - " -->"
  blanklines: true
  profile: false
pagination:
  enabled: false
  per_page: 2
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true